### ISSUE TITLE
Prototype REST API for retrieving books

### ISSUE THREAD

**Issue by zach-delong** [NCSU-CSC510-Group-E/CS510-Project1#7]

**Comment by ZacheryPD** [comment]
SO data can be downloaded [here](https://archive.org/details/stackexchange)
Conceptually, I think this code will work for the problem
```
document = iterparse("posts.xml", events=("start", "end"))
for event, elem in document:
print(elem.get('Id'))
elem.clear()
```

We can print to a file then and files can be easily understood.
